### PR TITLE
Add support for Israel TIN number

### LINKED ISSUE #107: Add support for Israel TIN
* I wasn't able to find the exact name (I found several with slight variations) so we will use the name referred in the government websites: מספר חברה (short version is ח.פ. )
* https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Israel-TIN.pdf
* https://wiki.scn.sap.com/wiki/display/CRM/Israel (9 digits, check digit calculated using Luhn)
* https://he.wikipedia.org/wiki/%D7%AA%D7%90%D7%92%D7%99%D7%93
* https://www.avalara.com/vatlive/en/country-guides/africa-and-middle-east/israel/israel-vat-registration.html
  > Format | 123456789
9 characters
For incorporated businesses, the first digit is a 5
* According to https://en.wikipedia.org/wiki/VAT_identification_number:
  > 9 digit number. If the number of digits is less than 9, then zeros should be padded to the left side. The leftmost digit is 5 for corporations. Other leftmost digits are used for individuals. The rightmost digit is a check digit (using Luhn algorithm).

Algorithm:
* Algorithm to calculate Identity number (using Luhn) https://he.wikipedia.org/wiki/%D7%A1%D7%A4%D7%A8%D7%AA_%D7%91%D7%99%D7%A7%D7%95%D7%A8%D7%AA#%D7%A1%D7%A4%D7%A8%D7%AA_%D7%91%D7%99%D7%A7%D7%95%D7%A8%D7%AA_%D7%91%D7%9E%D7%A1%D7%A4%D7%A8_%D7%94%D7%96%D7%94%D7%95%D7%AA_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C which according to https://he.wikipedia.org/wiki/%D7%AA%D7%90%D7%92%D7%99%D7%93 is the same algorithm used for TIN number.

Online search:
* https://www.gov.il/en/service/company_extract (links to page listed below)
* https://ica.justice.gov.il/GenericCorporarionInfo/SearchCorporation?unit=8 (this is only for companies, in other words it requires company number first two digits to be 51 through 59)
  * There are other online searchs for associations, etc.

Examples:
* https://441il.com/listco_res/%D7%A8%D7%9E%D7%95%D7%AA+%D7%9C%D7%99%D7%93+%D7%90%D7%95%D7%A0%D7%99%D7%91%D7%A8%D7%A1%D7%99%D7%98%D7%AA+%D7%AA%D7%9C+%D7%90%D7%91%D7%99%D7%91+%D7%91%D7%A2%D7%9E/Ramot+at+Tel+Aviv+University+Ltd/%D7%AA%D7%9C+%D7%90%D7%91%D7%99%D7%91+%D7%91%D7%A0%D7%99%D7%9F+%D7%94%D7%A1%D7%A0%D7%90%D7%98%2C%D7%A7%D7%9E%D7%A4%D7%95%D7%A1+%D7%90%D7%95%D7%A0%D7%99%D7%91%D7%A8%D7%A1%D7%99%D7%98%D7%AA+%D7%AA%22%D7%90++61392+39296/510667140.html
  > 510667140
* http://www.corporation.co.il/סקיוריטי-מטרס-בע"מ-515125771
  > 515125771
* https://next.obudget.org/i/org/company/515125771
* http://www.limited.org.il/515125771-%D7%A1%D7%A7%D7%99%D7%95%D7%A8%D7%99%D7%98%D7%99%20%D7%9E%D7%98%D7%A8%D7%A1
* https://datacheck.co.il/company.asp?ID=515125771

* https://rasham.bizportal.co.il/companies/printoutdetails?companyid=515125771
* https://www.local360.co.il/vat-details/513358/%D7%A1%D7%A7%D7%99%D7%95%D7%A8%D7%99%D7%98%D7%99-%D7%9E%D7%98%D7%A8%D7%A1-%D7%91%D7%A2-%D7%9E
* https://ipca.org.il/companies/%D7%A1%D7%A7%D7%99%D7%95%D7%A8%D7%99%D7%98%D7%99-%D7%9E%D7%98%D7%A8%D7%A1-%D7%91%D7%A2%D7%9E/
* http://www.getswot.com/company.asp?ID=515125771
* https://www.google.com/search?client=ubuntu&hs=rnD&channel=fs&sxsrf=ALeKk03cwK1DWi8ZaOL6Ib9jhMSNHnVvHA%3A1585556952173&ei=2K2BXv-fCs2cjLsPnviCkAE&q=wikipedia+%22%D7%9E%D7%A1%D7%A4%D7%A8+%D7%AA%D7%90%D7%92%D7%99%D7%93%22&oq=wikipedia+%22%D7%9E%D7%A1%D7%A4%D7%A8+%D7%AA%D7%90%D7%92%D7%99%D7%93%22&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAE6BAgjECdQlh9YwC9gqzpoAHAAeACAAZACiAGYBpIBBTAuMy4xmAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwj_657348HoAhVNDmMBHR68ABIQ4dUDCAo&uact=5
* https://www.israelbizreg.com/  (got to page 15, included, and there are still plenty more)
  > 516099280
516106945
516103264
516134392
516093069
516123890
516096369
516122645
516093150
516125135
516134764
560037046
516131265
516105616
516125135
516103686
516102886
516126067
516121761
516096393
516120169
516116340
516134145
516122207
516102266
516095742
516104973
516099611
516125853
516136918
516102266
516131745
516118064
516118973
516136264
516108453
516127289
516134277
516121373
516110913
516134277
516110913
516103041
516107380
516104148
516137270
516119682
516106432
516113008
516093549
516113008
516123668
516107380
516110418
516126141
516092095
516114972
516104817
516106937
516139060
516106937
516115003
516101136
516106879
516139060
516093499
516125549
516109360
516133709
516137536
516133709
516109360
516137536
516093739
516105111
516134319
516124963
516125424
516109626
516135977
516133030
516102001
516128493
516096245
516136074
516130283
516112745
516120557
516101227
516135977
516119377
516120557
516128204
516138179
516127941
516121720
516096351
516096419
516112026
516105012
516138179
516096351
516131026
516095155
516091998
516113461
516120235
516120284
516117900
516134012
516133113
516120235
516106002
516091998
516115128
516126760
516138930
516121530
516125499
516113768
516095544
516113768
516114865
516097615
516138930
516125499
516121530
516137213
516091667
516092624
516113693
516107372
516119153
516132867
516136041
516137775
516127719
516134715
516091667
516105277
516132602
516133774
516101854
516110996
516110616
516137734
516099157
516122413
516105277
516126208
* https://www.kycisrael.com/companies/  (got to page 2, included, but there are plenty more)
  > 540273471
516130317
540278512
540184942
540279544
550224299
550265193
550240824
550233696
530212331
550211270
550242861
530212976
540242070
540271855
530224211
530216845
540233129
540213642
550232839
512556069
514771401
511772840
513403857
511770281
511930828
514776426
514966993
515262475
512537986
512749532
530212984
511768749
514123215
540240884
515110047
520038266
550258008
540281359
540256468
550011498
512244245
512594342
511622375
515985232
514486356
516087152
512629254
514471127
514643519
514922467
514350024
513701169
514078138
513606582
515406031
515487668
512764788
512802174
512962010
514112044
512872359
514174341
514295062
513725440
515841690
515963627
515278380
514179019
513724187
514434737
512952268
513704999
540167285
515593200
515613776
515819605
514240761
515986198
512712373
512976028
515560217
513714543
515387876
514486182
513272971
514522226
515344935
515558096
515343598
514553007
514207661
515800431
515434041
513910869
514509918
512708363
515439958
514770494
513906420
* http://www.corporation.co.il/sitemap (several of the links here lead to company lists)
  > 511216129
512577214
510790256
512946948
514083096
512598137
512053521
510771314
510790272
513124982
513494146
510952328
511299588
512239732
513688481
514617570
510976103
512899667
513771519
512829375
514780352
510655525
512708074
514521996
513174813
514475284
513184119
515049757
513853085
514307107
512912742
511989790
513795948
514306042
514014950
512516014
514943174
510840432
512740861
513107334
513797027
510361371
514931138
512506643
513444224
512131228
511773897
512287731
512947276
511965576
511018590
540165982
515124386
514284603
511237018
514462282
510327307
510375330
515259430
513565473
515119964
513374355
515177129
511221947
511552440
513664755
512118654
512180266
513932962
513302588
513021741
515225233
513486381
515170546
513070839
511593667
511805822
512044264
511193815
511610966
513079582
515277440
514125798
512053968
511756108
510723182
512277021
512951526
511594418
513365080
512740630
513070623
513466532
511109977
513563080
511100554
511622490
512136417
512495540
511240350
515132082
513879205
513444836
512440934
514697358
512476789
513950741
514844653
540146420
512662628
513544833
514607290
514513357
514563469
510923402
511757593
515098671
511895286
514306844
514536648
* https://www.nevo.co.il/law_word/law10/yalkut-6642.pdf

### PR DESCRIPTION
**Pull request by unho**
Fixes #107.

### CODE REVIEW

**Comment by unho** [comment]
It is curious that Travis hasn't been run.

**Comment by arthurdejong** [comment]
Tarvis build is in. The build was failing but I don't know why it shows up now. I clicked around a bit in the Github and Tavis settings, retriggered the build and now it shows up.
I'm pretty busy at the moment so I didn't get around to checking the PRs yet. Will do so soon. Thanks for your work!

**Comment by unho** [comment]
@arthurdejong I hope you are ok. Will keep working on this PR and I expect to soon add some more.

**Comment by arthurdejong** [comment]
Thanks for your improvement. I have some issues with my dev environment which makes checking and merging stuff a bit of work but I'll try to merge more open PRs soon.

**Pull request closed without merging**
