### PR TITLE
add Australian number: ABN, ACN, TFN

### PR DESCRIPTION
**Pull request by vbastos**
Hey - Just thought I would add some Australian numbers to your module.

### CODE REVIEW

**Comment by arthurdejong** [comment]
Thanks for your contribution. There are a few minor bugs in your code but those are easily fixed.

Could you provide some small bit of text for each module's docstring? Perhaps with a pointer to more information.

Also do you know of any public registry or source of valid numbers of each type? For these kind of numbers I generally run tests against a large collection of found numbers and include a few in the test suite to try to avoid bugs (e.g. some numbers are documented to have a checksum but a significant percentage of real numbers fail the checksum test).

Thanks!

**Comment by vbastos** [comment]
Sorry about the bugs.

I'll update the branch with text for each module's docstring. I'll have a look at what I can get for you, but as far as I understand it there should not be any exceptions to the checksum.

Link for valid ACN's - http://asic.gov.au/for-business/starting-a-company/how-to-start-a-company/australian-company-numbers/australian-company-number-digit-check/

Links with information or validator - 
ABN - https://abr.business.gov.au/HelpAbnFormat.aspx
TFN - https://www.anao.gov.au/sites/g/files/net616/f/anao_report_1998-99_37.pdf

**Comment by arthurdejong** [comment]
I have made some modifications to your code and added some tests in 70b94ee, 8028c3a and 8ea76ba.

Thanks for providing your patch.

**Comment by vbastos** [comment]
Ah sorry Arthur! Thanks for closing that one off.

**Pull request closed without merging**
