### PR TITLE
Change DGII URL and Validation

### PR DESCRIPTION
**Pull request by jeffryjdelarosa**
DGII has changed their URL to validate, so with first take by BeautifulSoup __EVENTVALIDATION and __VIEWSTATE and then apply to make the post and the validation.

### CODE REVIEW

**Comment by arthurdejong** [comment]
Hi Jeffry,

Thanks for the improvement. The weird thing is that, with the old code, the tests still pass and things still appear to work.

Anyway, I've merged your change with minor changes as ac50afa.

**Comment by jeffryjdelarosa** [comment]
Yes, they restored back  their server, we had 3 days without connections,  but this minor changes, will first find the tokens, because their new server changes both tokens. Thank you so much.

In the other hands @arthurdejong we @gustavovalverde  need a new update on the official python-stdnun package or maybe a new version, of course if you can help us with it.

Thanks you so much.

**Comment by arthurdejong** [comment]
I plan on making a new release soon but it depends a bit on the time I have available.

**Comment by arthurdejong** [comment]
Hi @jeffryjdelarosa a 1.12 release of python-stdnum was just made.

**Comment by jeffryjdelarosa** [comment]
@arthurdejong Thanks you so much, @gustavovalverde

**Pull request closed without merging**
