### PR TITLE
Add support for Ghana TIN

### LINKED ISSUE #262: Add support for Ghana TIN
* https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Ghana-TIN.pdf
* According to https://gra.gov.gh/online-tools/verify-tin/ the format is: This is how a TIN looks, starts with a C / P followed by 10 digits making 11.
* Format `C000XXXXXXX` according to http://world.salestaxhandbook.com/gh-ghana and https://vat.international/ghana/
* https://gra.gov.gh/tin/
  * It is called `Taxpayer Identification Number (TIN)`.
  * Note that `Ghana Card Personal Identification Number (Ghana card PIN)` is used as TIN for individuals.
* https://gra.gov.gh/tin/tin-faq/

Online validation:
* https://gra.gov.gh/online-tools/verify-tin/
  * As stated in that page: `This tool is only for Personal TIN verification and not for Company TIN`
* Maybe other alternatives mentioned in https://www.tellitnurse.com/2021/01/how-to-verify-tin-number-and-business.html

Examples:
* `C000261992X` from https://ghana.tradeford.com/gh706546/
* `C0000803561` from https://landmatrix.org/media/uploads/gragovghdocsinfotema_self_assess_mtopdf.pdf
* `C0005015774` from https://www.libertyhealth.net/ghana/en/contact-us/
* https://gra.gov.gh/publication-of-names-of-directors-of-defaulting-companies/
  * `C003585891`
  * `C0009705228`
  * `C0004894162`
* `C0004656830` from https://www.izweghana.com/
* https://www.gheiti.gov.gh/site/index.php?option=com_phocadownload&view=category&id=35:mining-oil-a-gas-reports&download=402:2019-gheiti-miniing-sector-report&Itemid=&Itemid=54
  * C0003268071
  * C0003257630
  * C000313697
  * C000327828X
  * C0004056450
  * C000366497X
  * C0002442477
  * C0003257673
  * C0003137007
  * C0003278263
  * C0003278484
  * C0003165493
  * C0002862646
  * C0003278271
  * C0004524764
  * C0003136973
* `P0008816751` from https://accra.yalwa.com.gh/ID_136359792/ESCA-TECH-ELECTRICAL-COMPANY-Ltd.html
* https://myinfo.com.gh/2020/09/the-dominica-registered-company-behind-kotokas-150-coronavirus-test/
  * P0009487379
  * P0001525662
  * P0009329250
  * P0009329188
* `C0029454158` from https://melbet.com.gh/line/ice-hockey/2277430-heart-cup/144431665-flames-clan/
* https://ccma.gov.gh/images/documents/reports/2020_MDAs_Report.pdf
  * C0003417425
  * C0002147866
  * C0010952330
  * C001095242X
  * C0005203333
  * P0004697499
  * V0022862404
  * C0013225812
* `G0061140708` from https://keeama.gov.gh/wp-content/plugins/download-attachments/includes/download.php?id=1947
* `C0003442500` from https://gse.com.gh/docs/PR_291_Izwe_Loans_Limited_Coup.pdf
* `C0006570275` from http://wacci.ug.edu.gh/wacci-ace/sites/default/files/2018-09/Claim%20No%206_1.pdf
* https://audit.gov.gh/files/audit_reports/Report_of_the_Auditor-General_on_the_Public_Accounts_of_Ghana_-_Ministries,_Departments_and_other_Agencies_for_the_year_ended_31_December_2021.pdf
  * P0039937100
  * P0006187994
* https://www.gheiti.gov.gh/site/index.php?option=com_phocadownload&view=category&id=35:mining-oil-a-gas-reports&download=403:2019-gheiti-oil-and-gas-sector-report&Itemid=54
  * V0003107108
  * C0002551888
  * C0003168417
  * C0003831426
  * C0003664996
  * C0004743520
  * C0021485674
* `P0012631833` from https://webapps.knust.edu.gh/staffportal/assets/uploads/CVs/3bfcd1929913d3bead2bb364d7f5ba96.docx
* `G0005513405` from https://mlnr.gov.gh/wp-content/uploads/2020/08/Central-Region_-Mineral-Royalties-2017-2018.pdf
* `C0021793506` from https://www.facebook.com/107273044095142/photos/a.108071384015308/108139370675176/

### PR DESCRIPTION
**Pull request by unho**
Fixes #262.

### CODE REVIEW

**Comment by arthurdejong** [comment]
It seems that most of the numbers that start with a C or V from the tests do not validate on https://gra.gov.gh/online-tools/verify-tin/

The C numbers sometimes end with an X which suggest that the last digit is a check digit.

**Comment by unho** [comment]
@arthurdejong in that page there is the following warning:
> This tool is only for Personal TIN verification and not for Company TIN

That explains why none of the non-P Ghana TIN numbers validate there.

**Comment by unho** [comment]
@arthurdejong I have been trying to find some way to verify company TIN numbers for Ghana online, but I only could find some URL that doesn't load. I have updated the ticket with a link to the page where I found that URL.

**Comment by arthurdejong** [comment]
Thanks for pointing out the noticed I missed on the https://gra.gov.gh/online-tools/verify-tin/ service. There seems to be [another portal](https://egovonline.gegov.gov.gh/RGDPortalWeb/portal/RGDHome/eghana.portal?_nfpb=true&_st=&_pageLabel=portal_RGDHome_NameSearchPage_page&linksPageTitle=Name+Search&service=namesearch#wlp_portal_RGDHome_NameSearchPage_page) but that doesn't support searching on the TIN and neither shows it. [This site](https://rapps.gegov.gov.gh/tripsutil/tinsearch.jsp) seems to be unreachable.

I did look at the numbers and the check digit calculation seems to be exactly the same as ISBN10 so I've added a check digit calculation function and merged it as 7be2291.

**Pull request closed without merging**
