### PR TITLE
DGII Services change SSL validation and verification.

### PR DESCRIPTION
**Pull request by jeffryjdelarosa**
This a a new way with disable SSL since August 30th DGII has change their SSL validation. All our customer is down becasue of this.

### CODE REVIEW

**Comment by jeffryjdelarosa** [comment]
@arthurdejong the Zeep library is no installed.

**Review by fow903 — APPROVED** [review]
LGTM!

**Review by raulovallet — APPROVED** [review]
Nice, Many people are waiting for this, thank you!!!

**Review by jose250698 — APPROVED** [review]

**Review by kvillar93 — APPROVED** [review]

**Comment by arthurdejong** [comment]
Hi @jeffryjdelarosa,

Thanks for your contribution. In 3fcebb2 I've added support for verifying certificates for all network services. I think this covers all the cases that this PR was meant to resolve. If that is not the case feel free to re-open this PR.

**Comment by jeffryjdelarosa** [comment]
It's a pleasure, thanks @arthurdejong !

**Pull request closed without merging**
