### PR TITLE
Add support for Taiwan TIN number

### LINKED ISSUE #209: Add validation for Taiwan TIN
* It is called 統一編號  according with http://www.foxsemicon.com/chinese/index.php  and other sources. In English it is called "Unified Business No." or "Unified Business Number", being "UBN" the acronym.   
* Algorithm:   https://wilhelmliao.wordpress.com/2011/05/10/taiwan-unified-business-number-validation/
* https://zh.wikipedia.org/wiki/%E7%B5%B1%E4%B8%80%E7%B7%A8%E8%99%9F
* It is 8 digits according to several sources and all found examples.
* http://world.salestaxhandbook.com/tw-taiwan
* https://www.findcompany.com.tw/en/ECHO%20CHEMICAL%20CO.,%20LTD.

Search online:
* https://findbiz.nat.gov.tw/fts/query/QueryBar/queryInit.do?request_locale=en

Algorithm:
* https://wilhelmliao.wordpress.com/2011/05/10/taiwan-unified-business-number-validation/
  * Great explanation, but there are some actual valid numbers this simplified algorithm does not catch, so we will be using a more complex version outlined in some of the other implementations below.
* Several algorithms, in PHP, including UBN https://github.com/cakephp/localized/blob/master/src/Validation/TwValidation.php
* https://blog.darkthread.net/blog/sl3-validation-notes/
* http://linuschien.blogspot.com/2013/01/bean-validation-jsr303_10.html
* https://dotblogs.com.tw/rainmaker/2009/12/09/12351

Examples:
* http://rrfp.swcb.gov.tw/Common/SelectGOVE_COMM_Serch?gvUC_GOVE_COMM-orderBy=TAX_ID-desc
  > 99963479
99940188
99939176
99937037
99936918
99933010
99931596
99924933
99924856
99923857
99917187
99906772
99906338
99904177
99900670
99899738
99894425
99892600
99884812
99879748
99878419
99875829
99870916
99869164
99866384
99863078
99861923
99856230
99856127
99855648
99853521
99852115
99851848
99851093
99849512
99848387
99842031
99841053
99838705
99833899
99833645
99830984
99830984
99809976
99805628
99795641
99793720
99787065
99786158
99784089
99773040
99757338
99757338
99756176
99749204
99745468
99744572
99736030
99696641
99693010
99691548
99689965
99688662
99685932
99685594
99685594
99685399
99676878
99675060
99674230
99671070
99669905
99669362
99669193
99668336
99668125
99668053
99668048
99668027
99667982
99665979
99664958
99663965
99659688
99659189
99658392
99653306
99651948
99645502
99617631
99596468
99596220
99595989
99595313
99595290
99592765
99591077
99587926
99581140
02811618
02811595
02811574
02811286
02810884
02810478
02810370
02810218
02809606
02757558
02750963
02695934
02612809
02550590
02415271
02276405
02255422
02255416
02255181
02255149
02253753
01993858
01819129
01671049
01232020
01201173
01200673
01050772
01032108
01031918
01012715
01012449
01009232
01006018
00992156
00969726
00966299
00965117
00965067
00958235
00957524
00508203
00501932
00277408
00277104
00038603
* https://depart.moe.edu.tw/ED4100/Content_List.aspx?n=6548379386D6E093
  > 03737200
57302906
03723901
81580767
52020800
52697649
08203324
08095676
73761420
05600284
03734105
03729406
03735505
17881751
03734203
  > 
  > 76211194
45002931
06313774
52024101
46804706
69115908
06476734
02415271
08153719
02080958
99033073
91004005
03807654
19880949
76014004
46804804
03734246
10094548
66019206
58815502
01014220
52009903
10617383
76905842
03729709
99335422
93504006
69116104
97960503
03734301
03753600
03787502
64847502
03735202
00501503
95927022
02612744
52011008
  > 
  > 64967512
91004103
76014406
77495542
06195262
57301337
52010606
92021164
03763608
03729807
69116505
04126516
03813207
77187931
  > 
  > 60900309
21335447
25329369
13534274
52010704
61611405
87814088
45000103
19615034
60903805
64004306
66022602
73503009
12071795
56503139
58809403
40403401
88507003
88504104
91605507
57701707
43503707
94510202
77355373
77355514
61616507
61611307
09561093
14293457
91746936
25821829
91003907
71802305
91605801
99326850
74877286
49508709
60004304
60004901
60004108
60004206
62302201
36445457
61611502
96402805
81141938
00921630
00520500
58809305
66012105
73504106
73503107
46803306
99505100
71804508
71804508
45002904
66007406
87675543
66018804
66018608
66019304
66018706
58815405
87402500
87402608
62300415
52010205
20395255
52003008
55508115
02999681
52010009
52010107
04173812
78862616
93504300
93504202
93504408
69116408
73503205
69116701
69514291
69116202
03731705
85509409
92502402
96076702
42005007
57303406
40407602
* Found on the Internet:
  > 12858252  from http://www.foxsemicon.com/english/index.php
54664996  from https://www.eulerhermes.com/en_TW/legal.html
86489893  from http://www.danisbustour.com/files/11-1000-107.php
28148905  from http://www.nkstech.com.tw/yellowpage/
24932469  from https://www.kalin.com.tw/index_en
28425197  from https://ipc2u.com/about-us/ipc2u_world/
24718587  from http://www.chinlin.com.tw/info.html
28315353  from http://en.topmso.com.tw/downloadarea/20180522165128.pdf
80542111  from https://www.liberty.com.tw/en/about/index3.aspx?kind=40
28410552  from https://www.sec.gov/Archives/edgar/data/1158114/000101968716006020/appliedopto_8k-ex1001.htm
53084078  from http://www.chso.com.tw/front/bin/ptlist.phtml?Category=12
54381049  from https://web.tigerairtw.com/en/conditions-carriage-2/
80173854  from http://www.arkfilms-tp.com/contact_en.php
84566661
66607099
59372104
96895907
11337775
29116418
23357403
76901917
04111302
11395000
89802496
28403834
84846045
53020997
22952538
12729928
03702716
12682114
01013257
70849231
70618800
23876186
53412564
09258521
21100531
53235414
45888690
27232159
16087755
29137568
22822281
12800766
28674499
24890496
80158777
24542672
50756163
78962740
50872698
08551977
54663032
05600361
89398405
91004005
08149429
03724606
27940723
69795525
96402805
69115908
56503102
71803607
29902605
00501503
76001900
99335422
17713214
87814088

### PR DESCRIPTION
**Pull request by unho**
Fixes #209.

### CODE REVIEW

**Comment by unho** [comment]
I am not sure why Travis fails.

**Comment by pokoli** [comment]
@unho Travis is failing when building the docs beucause there is a warning on it: 

> /home/travis/build/arthurdejong/python-stdnum/docs/stdnum.in_.aadhaar.rst:2:Unknown target name: "stdnum.in".

You should fix it to make travis happy.

**Comment by arthurdejong** [comment]
Hi @unho 
I've merged your PR as dab926c with a minor change: I've renamed `calc_check_digit()` to `calc_checksum()` because that is what it really did (it would not calculate the correct check digit for an arbitrary number).
Thanks!

**Comment by unho** [comment]
@arthurdejong Thanks! Not sure when you are going to proceed with next release. I would like to also include PR #199 in next release, which is still work in progress, so I will try work on it one of these days.

**Pull request closed without merging**
