### PR TITLE
Add support for South Korea TIN Number

### PR DESCRIPTION
**Pull request by unho**
Sadly I have not been able to find the algorithm to calculate the check digit. I sent an email to the contact point, but I still have not got any response. Anyway this provides basic format checking that should be of some help.

Part of #101

### CODE REVIEW

**Comment by unho** [comment]
@arthurdejong I don't see what is breaking the tests, any idea?

**Comment by unho** [comment]
@arthurdejong I have found the cause.

**Comment by unho** [comment]
@arthurdejong IMHO this can be landed with check digit validation. If we manage to find out how the algorithm is we can add it later.

**Comment by arthurdejong** [comment]
Thanks, I've merged it as b3891f1 without the check digit validation for now. I've also added a function to perform an online check in 1b7e985.

**Pull request closed without merging**
