### PR TITLE
Add support for Costa Rica TIN number

### LINKED ISSUE #109: Add support for Costa Rica TIN
Details on the format:
* https://www.hacienda.go.cr/consultapagos/ayuda_cedulas.htm
* Details on the format in table at bottom of page 11 of https://www.procomer.com/downloads/quiero/guia_solicitud_vuce.pdf
* Types of Cédula Jurídica: http://www.registronacional.go.cr/personas_juridicas/documentos/Consultas/Listado%20de%20Clases%20y%20Tipos%20Cedulas%20Juridicas.pdf
* https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Costa-Rica-TIN.pdf
* https://en.wikipedia.org/wiki/VAT_identification_number

Online query:
* Query in https://www.hacienda.go.cr/ATV/frmConsultaSituTributaria.aspx

Examples:

* http://www.registronacional.go.cr/Listado%20de%20Disolucion%203.xlsx
* Seems to be previous document in another format https://www.imprentanacional.go.cr/pub/2017/05/25/ALCA111_25_05_2017.pdf
* More examples (that have to be extracted by hand) in http://www.aselex.cr/boletines/Gaceta/GAC2018-07-02.pdf (plenty of them listed below)

* Examples (Cédula persona jurídica):
3-101-999999
3-101-121231
3-101-051324
3-102-159181
3-007-051185
2-100-042005
3-102-010536
4-000-042145
2-200-042153
3-101-123456
(not yet verified below)
3-101-082390
3-007-655746
2-100-042011
3-007-078890
2-100-042000
4-000-001021
3-007-559723
4-000-001128
3-007-042037
3-013-746748
3-007-317912
3-014-042116
3-007-042039
3-002-045556
3-101-587412
2-100-098311
2-300-042155
3-007-351220
4-000-042149
2-100-042002
3-101-754574
3-101-228154
3101212106
3101754615
3101195856
3101420995
3-101-420995
3007117191
3101265235
3101317433
3101414841
3101724003
3101023590
3-101-085076
3101745157
3102749025
3006245959
3101721442
3101269160
3101080710
3-101-395811
3-101-052431
3102749784
3101734486
3101737387
3101042789
3101205939
3101753991
3-101-077629
3-002-118350
3-002-670350
3-002-363949
3-002-051235
4-000-042138
3-101-175991
3102039372
3-101-714733
3014042093
3-101-747406
3-102-569988
3-101-32541    (sometimes leading zeroes are omitted in each group)
3-102-476080
3-006-227840
3-101-260579
3-101-557152
3-101-756187
3-009-117444
3-102-476080
3-101-279978
3-101-450947
3-101-642402
3-101-262124
3-102-631690
3-101-407575
3-101-279978
3-101-450947
3-101-50217
3-101-366365
4-000-042149

### PR DESCRIPTION
**Pull request by unho**
Fixes #109.

### CODE REVIEW

**Comment by unho** [comment]
@arthurdejong I've looked if this uses some sort of verification and I've found nothing, so we are just checking for format.

**Comment by unho** [comment]
Also added support for Costa Rican nationals ID number and partial support for Costa Rican foreigners ID number. I won't be completing the latter implementation.

This PR is ready for final review.

**Comment by arthurdejong** [comment]
Thanks again for providing these implementations! I'm trying to review and merge then as quick as possible :smiley:

**Comment by unho** [comment]
Thanks for reviewing! I am still looking to add a few more, probably next weekend.

**Pull request closed without merging**
