### PR TITLE
Add support for Indonesia TIN number

### LINKED ISSUE #106: Add support for Indonesia TIN
* https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Indonesia-TIN.pdf
* https://wiki.scn.sap.com/wiki/display/CRM/Indonesia
* (found in previous page) https://www.online-pajak.com/kode-seri-pada-npwp

Validation:
* Online validation https://sse3.pajak.go.id/registrasi (doesn't seem to work)
* Code that validates by querying online validation https://sse3.pajak.go.id/cekWsDataWp
  * Python: https://pypi.org/project/npwPy/
  * PHP: https://github.com/hz081/npwp-checker
* Perl: https://metacpan.org/pod/Business::ID::NPWP
* Perl: https://metacpan.org/pod/release/SHARYANTO/Business-ID-NPWP-0.02/lib/Business/ID/NPWP.pm
* Spreadsheet found in https://www.npwponline.com/2016/08/validasi-npwp-online.html using Luhn algorithm.
* https://techscales.blogspot.com/2016/08/validasi-npwp.html seems to us Luhn algorithm as well.
* According to documentation in Perl script the check digit is calculated using Luhn algorithm.

Examples (some of them don't validate using Luhn, and there are repeated numbers):
* Found on the Internet:
  > 01.001.634.3-093.000
76.310.346.2-601.000
02.037.103.5-502.000
01.318.451.0-054.000
* By clicking on the companies listed in https://www.idx.co.id/en-us/listed-companies/company-profiles/ we can get their NPWP.
  > 01.334.427.0-054.000
01.609.052.4-017.000
01.362.014.1-054.000
02.504.191.4-054.000
01.721.123.6-054.000
01.709.626.4-054.000
01.001.610.3-051.000
01.326.008.8-092.000
02.399.244.9-091.000
02.881.392.1-036.000
01.002.124.4-038.000
01.347.428.3-018.000
01.311.830.2-073.000
01.360.902.9-054.000
01.820.068.3-054.000
01.504.513.1-054.000
02.038.425.1-054.000
01.000.863.9-054.000
01.132.905.9-092.000
01.349.129-5-054-000
01.671.242.4-054.000
01.000.166.7-054.000
01.122.572.9-092.000
01.761.303.5-405.000
01.108.165.0-073.000
01.000.161.8-092.000
* https://lpse.jabarprov.go.id/eproc4/dl/92fd75e21cf1397a2f88893f0fc5c319a8853e5baa63b2a24dd80c290fdb2a98703a433ef980183a240354473681980f7cf3778c5a84d0eef92b55891b13a1f335f0de9cfc0af8b6f510ced0867c7cb7cb9a33dbd0218fcd611d7ca8cdb2b8c5
  > 02.554.459.4-422.000
02.098.700.4-013.000
02.098.788.9-013.000
02.244.448.3-428.000
01.210.739.7-424.000
01.421.821.8-424.000
01.436.246.1-429.000
01.216.217.5-441.000
02.207.332.6-606.000
01.349.759.9-083.000
31.281.245.8-423.000
02.481.070.7-423.000
02.972.041.4-428.000
31.470.209.3-428.000
03.187.078.5-201.000
02.587.597.2-429.000
02.567.804.6-428.000
02.241.591.3-424.000
01.455.616.1-424.000
02.333.122.6-441.000
* http://inatrade.kemendag.go.id/index.php/home/detail_hakAkses
  > 748575982452000
846150324629000
010692903641000
811145994124000
210614467418000
764038907023000
817434558048000
825537079086000
762278075077000
017048299643001
721437267602000
813195435017000
755023033513000
014300040123000
317784585606000
* http://lpse.simeuluekab.go.id/eproc/lelang/pemenang/123383;jsessionid=A1BCFEB86E1D32263828B47C2A6E1E17
  > 01.931.919.3-101.000
03.030.253.3-104.000
02.071.363.2-101.000
02.887.783.5-105.000
02.650.677.4-101.000
02.561.935.4-101.000
03.128.360.9-101.000
02.008.503.1-101.000
01.548.452.0-429.000
01.855.599.5-101.000
02.151.039.1-106.000
02.690.654.5-101.000
01.452.340.1-101.000
31.538.040.2-106.000
02.071.326.9-101.000
02.888.370.0-106.000
02.932.094.2-101.000
02.956.222.0-106.000
02.976.331.5-103.000
02.502.873.9-101.000
31.496.676.3-106.000
01.575.888.1-101.000
01.657.878.3-101.000
02.102.011.0-101.000
02.956.223.8-106.000
01.931.919.3-101.000
02.719.242.6-106.000
* http://lpse.pesisirselatankab.go.id/eproc/lelang/pemenang/1181599;jsessionid=UiSgKR0Sn_kk0k4UBDJGrt99qT-rXqpHKfhGNl23
  > 01.688.820.0-201.000
02.872.808.7-201.000
83.132.665.7-201.000
02.551.560.2-201.000
01.688.745.7-201.000
02.585.033.0-216.000
01.508.687.0-201.000
02.717.384.8-201.000
01.129.103.6-201.000
76.326.884.4-205.000
90.004.581.6-201.000
02.718.070.2-201.000
01.268.444.5-201.000
03.244.868.0-201.000
74.654.394.1-201.000
02.998.227.9-201.000
02.984.042.8-201.000
84.054.217.9-609.000
01.268.426.2-201.000
01.987.068.2-216.000
70.838.297.3-201.000
01.580.769.6-201.000
31.578.913.1-201.000
71.269.216.9-203.000
31.682.116.4-201.000
01.129.154.9-201.000
01.580.849.6-201.000
01.622.873.6-201.000
01.633.544.0-311.000
82.790.415.2-205.000
80.742.886.7-201.000
31.696.264.6-201.000
02.668.150.2-201.000
01.917.470.5-201.000
01.230.106.5-201.000
01.258.022.1-201.000
01.688.820.0-201.000
* https://lpse.sulselprov.go.id/eproc/lelang/pemenang/5144036;jsessionid=1PCEq-7yB94OEiKXKzt_EcVPxT8pRqgOnkBhZ7Uv
  > 02.934.102.8-804.000
02.679.257.2-801.000
01.000.483.6-051.000
01.796.259.8-805.000
02.547.885.0-805.000
02.661.025.3-805.000
01.906.354.4-801.000
02.056.129.6-801.000
01.211.695.0-805.000
01.211.695.0-805.000
03.026.787.6-805.000
20.811.634.1-801.000
76.992.174.3-802.000
01.690.679.4-801.000
01.815.656.2-807.000
01.502.718.8-805.000
01.690.980.6-805.000
02.934.102.8-804.000
02.636.703.7-814.000
01.773.770.1-805.000
75.193.535.4-805.000
03.217.024.3-805.000
02.643.101.5-805.000
01.125.612.0-805.000
02.303.892.0-801.000
02.974.105.5-801.000
03.195.088.4-801.000
01.562.420.8-805.000
02.910.648.1-805.000
01.966.099.2-801.000
* http://lpse.bandung.go.id/eproc/lelang/pemenang/1711260;jsessionid=2516644769B29C45712599E4D222CC44
  > 02.480.884.2-444.000
02.332.747.1-429.000
01.436.246.1-441.000
31.154.173.4-411.000
01.450.058.1-423.000
01.822.790.0-441.000
31.777.549.2-429.000
01.210.739.7-424.000
02.300.607.5-429.000
31.156.437.1-002.000
02.173.740.8-002.000
01.627.251.0-404.000
31.729.429.6-542.000
02.527.123.0-017.000
31.460.812.6-071.000
02.790.820.1-428.000
02.065.356.4-429.000
01.970.323.0-424.000
02.203.654.5-429.000
02.446.000.8-429.000
01.822.790.0-441.000
01.677.930.8-429.000
01.548.436.3-423.000
01.482.738.0-424.000
01.677.956.3-428.000
02.682.759.2-542.000
01.216.271.5-441.000
02.564.234.9-421.000
66.487.591.1-071.000
01.105.197.6-424.000
02.083.962.7-422.000
02.480.873.5-423.000
21.078.367.6-424.000
80.502.237.3-541.000
01.555.547.7-429.000
01.910.250.8-429.000
01.977.486.8-429.000
31.294.519.9-424.000
01.455.616.1-441.000
01.118.819.0-441.000
01.421.821.8-424.000
02.081.228.5-424.000
02.241.591.3-424.000
02.480.884.2-444.000
* https://lpse.pu.go.id/eproc/lelang/pemenang/4013064;jsessionid=3U0P47ykTTRXOBNg7io5P9iF4LeTTwYUo2NR9Duk
* https://lpse.slemankab.go.id/eproc/publicberitadetail/223054;jsessionid=FmMtmpcxskRz730GhDzR_DKkidQuuzclltHcjfUJ
  > 01.464.753.1-542.000
01.544.103.3-545.000
01.207.840.8-542.000
02.755.249.6-541.000
01.544.009.2.543.000
* http://simpbj.cirebonkab.go.id/
  > 86.127.083.3-426.000
01.997.870.9-038.000
01.457.751.4-426.000
01.457.751.4-426.000
02.367.986.3-426.000

### PR DESCRIPTION
**Pull request by unho**
Fixes #106.

### CODE REVIEW

**Comment by unho** [comment]
@arthurdejong This PR does not contain code to use the available API (more info on the issue), but I don't plan to add code for it. Anyway it seems pretty simple and there are some implementations available to mimic, including one in Python.

**Comment by arthurdejong** [comment]
Thanks! Merged as 7112874. I don't think the API to do online validation works any more. The hope page shows a login screen and I think the PHP version you linked also does a login there.
Btw, I will get around to the other pull requests but it'll take a bit of time, sorry for that.

**Comment by unho** [comment]
@arthurdejong Thanks. Any chance we get a release soon?

**Comment by arthurdejong** [comment]
@unho I plan to make a release "somewhat soonish" sorry to not be more precise but it depends a bit a available time and what should be included (mostly going over open PRs).

**Pull request closed without merging**
