### PR TITLE
Add support for Singapore TIN Number

### LINKED ISSUE #111: Add support for Singapore TIN
* https://www.oecd.org/tax/automatic-exchange/crs-implementation-and-assistance/tax-identification-numbers/Singapore-TIN.pdf
* https://www.uen.gov.sg/ueninternet/faces/pages/admin/aboutUEN.jspx
* https://carina.gov.hr/UserDocsImages//dokumenti/CTVP//Mogu%C4%87e%20varijante%20UEN%20brojeva.pdf
* https://sleek.sg/2019/10/02/what-is-uen-in-singapore/
* https://wiki.scn.sap.com/wiki/display/CRM/Singapore
* https://www.sgbt.lu/fileadmin/user_upload/SGBT/PDF/Compliance/CRS_2018/20191031_TIN_Leaflet_EN.pdf

Search company online:
  * https://www.uen.gov.sg
  * https://www.iras.gov.sg/irashome/GST/GST-registered-businesses/Other-services/Checking-if-a-Business-is-GST-Registered/

Validation:
  * https://gist.github.com/mervintankw/90d5660c6ab03a83ddf77fa8199a0e52

Examples:
  * Database with real UEN numbers: https://data.gov.sg/dataset/entities-with-unique-entity-number
    > T19LL0797J
T18LL1393C
T18FC0083E
T17LL2098G
T17LL1494G
T17LL0235L
T16LL1853E
T16LL1392H
T16LL0695L
T16LL0053J
T15LL1956A
T15LL1855C
T15LL1753J
T14LL1800D
T14LL1743K
T14LL1681C
T14LL1237A
T14LL0839C
T14FC0094H
T13LL0828H
T12LL2127H
T12LL2046J
T12LL0781D
T12LL0595L
T11LL2079G
T11LL1971L
T11LL1149C
T11LL0668C
T10LL1848E
T10LL1480E
T10LL1442K
T10LL1400J
T10LL1392L
T10LL1298G
T08LL1615B
T08LL1558H
T08LL0979J
T07LL0668H
T07LL0309A
T06LL0476A
T05LL0174J
T01FC6132D
S96FC5128K
S85FC3621C
S73FC2294C
S68FC1890G
S64FC1644H
S16FC0121D
53400433D
53399659K
53399638D
53399589B
53398169K
53397681B
53395867M
53395684J
53394981E
53393519M
53393390X
53393038C
53392959L
53385401J
53384425L
53384385E
53384227A
53383991B
53383940L
53382783C
53382124W
53381136L
53380232J
53377824K
53377498E
53377389W
53374706J
53374421X
53374181E
53374159M
53373737X
53373376J
53373278J
53372960B
53372845B
53372084B
53371741L
53369357L
53369142K
53368090E
53366669D
53366537W
53365157C
53365141K
53365050W
53363709X
53363526L
53363453M
53360906B
53360367J
53360246K
53360148K
53359796W
53359192M
53358936C
53358412D
53358098J
53357813B
53357438B
53354912D
53352926C
53352847W
53351301D
53349478L
53347826W
53346756W
53346603B
53346524M
53344927L
53343978K
53343146L
53341298J
53341233A
53341171L
53340486W
53340108M
53339826J
53339287W
53338593L
53338455M
53337959L
53337633E
53337452M
53337382D
53337313A
53336671B
53336471W
53334750E
53333709K
53333269M
53330210B
53329865B
53329644K
53328294B
53327223L
53326012D
53325701L
53325085D
53324543E
53322268X
53321041X
53320609W
10841100A
10839500J
10655900A
10555800A
10528100W
10482100X
10415300L
10362000A
10185500A
10080700C
09623000B
09402000X
08791100X
08511500B
08301600K
08268300W
07846200B
07609900L
07392800C
07330000D
07179600B
07088800X
07059900M
07046800A
07038800L
06905300J
06540200J
06273700K
06108900A
06018700W
05827100K
05796700L
05682800D
05598000K
05473700A
05346600D
05328700B
05040200E
05016600W
03989700A
03875300J
03122200E
03076400M
02708900B
02570100B
02143900A
01680100L
01402200A
00416700K
00192200M
  * Company list https://www.sgpbusiness.com/browse/A
    > 201602902K
201316157E
  * Company list https://directory.singaporefintech.org/directory/listing 
    > 201732074H
201620388N
200509725E
201605323H
201543956D
201330175G
201626104W
S27FC0556D
201102634H
201704172Z
201814975K
200001838R
200204038R
201533374C
201731364D
201506999D
201810763C
200612239R
201808454H
201831257M
201509563K
198700821N
201723655Z
201801863N
200402245Z
201528593H
201830835R
201422013M
200601141M
201525866W
201508961K
201608874E
201528239N
201507276Z
201405619W
201616811C
201539125W
201621244C
201813990E
201312700G
201107298M
201529785D
201610912H
201819215N
201613871H
201814325Z
201314109K
S73FC2302A
201427857E
199201624D
199903512M
201931750M
199701117H
201506513W
200717119C
201610327H
201227749M
201434292D
201008183D
S99FC5759D
201630906R
200613692K
201128195W
201630570C
200003956G
199607747H
201722949W
T08LL0721A
T09LL1649F
201838963W
  * Company list https://techasean.io/en/entity/?q=&countryOrigin=Singapore&role=
    > 201933247R
201317775M
200911532W
201118211H
53143018M
201430557E
201421015W
201703509H
  * https://graduatestudies.smu.edu.sg/sites/graduatestudies.smu.edu.sg/files/List%20of%20Projects%20on%20PIP_0.pdf
    > 200311327H
201828636K
201504218R
201728348W
201114628K
198101793G
201026348Z
199103870C
201105107Z
201221002E
200923096R
201706114W
198601642R
201730487Z
  * Found on the Internet:
    > T01SS0121K
201524437R
200503573Z
201001206N
201323386K
201927572K
201505714C
201902616N
201834016K
201804195C
T08LL0005E
201729145M
201539692G
201831267E
201530032R
S65SS0033F
199700895N
199409389H
201928835M
201422211Z
201612228W
200806526H
201735853W
199407631H
53380578C
201538146W
S66SS0041B
T08LL0003B
201709179W
200004389G
S86SS0040A
201225997K
201541306Z
S60FC1376L

### PR DESCRIPTION
**Pull request by unho**
Fixes #111.

### CODE REVIEW

**Comment by unho** [comment]
@arthurdejong Ready for review.

**Comment by arthurdejong** [comment]
Thanks for the PR. Sad about not being able to get the documentation on the check digit algorithm. However, since there is such a [large dataset of valid numbers](https://data.gov.sg/dataset/entities-with-unique-entity-number) published it is actually not that hard to reverse engineer the algorithm.

First I looked at the distribution of the check digits across the numbers and found that they were not evenly distributed. However when filtering the numbers by type I found:

- when looking only at the business numbers the check characters are evenly distributed across the letters ABCDEJKLMWX
- when looking only at the local company numbers the check characters are evenly distributed across the letters CDEGHKMNRWZ
- when looking only at the other numbers the check characters are evenly distributed across the letters ABCDEFGHJKL

This seems to suggest a mod 11 algorithm where the check digit alphabet is different based on the type. When assuming a simple weighted algorithm we can try to guess the weights.

Looking only at the business numbers for now we can generate groups of numbers that only differ in the last (before the check digit) number and check how the last digit changes the check digit:

```python
sames = defaultdict(list)
for number in numbers:
   sames[number[:7] + 'x'].append(number)
complete = [number for number, values in sames.items() if len(values) == 10]
for i in range(5):
    number = random.choice(complete)
    print('%s %s' % (number, ''.join(x[-1] for x in sames[number])))
```
```
5286165x AWLJDBXMKE
5336500x CAWLJDBXMK
5310314x CAWLJDBXMK
5313062x LJDBXMKECA
5322613x ECAWLJDBXM
```

This shows that the check digit alphabet is `MKECAWLJDBX` or some rotation of it. Continuing to the second digit from right:

```python
sames = defaultdict(list)
for number in numbers:
   sames[number[:6] + 'x' + number[7:8]].append(number)
complete = [number for number, values in sames.items() if len(values) == 10]
for i in range(5):
    number = random.choice(complete)
    print('%s %s' % (number, ', '.join(str(alphabet.index(x[-1])) for x in sames[number])))
```
```
530705x5 9, 5, 1, 8, 4, 0, 7, 3, 10, 6
531093x1 6, 2, 9, 5, 1, 8, 4, 0, 7, 3
533736x9 0, 7, 3, 10, 6, 2, 9, 5, 1, 8
528194x1 4, 0, 7, 3, 10, 6, 2, 9, 5, 1
532139x3 6, 2, 9, 5, 1, 8, 4, 0, 7, 3
```
This shows that every time the x goes up one the check digit goes down by 4, which implies the weight should be 7 (-4 mod 11).

Doing this for every digit (the first digit requires a bit of tweaks because only values from 0 to 5 are found) and shifting the alphabet a bit to get the correct offset we get:

```python
def calc_business_check_digit(number):
    number = compact(number)
    weights = (10, 4, 9, 3, 8, 2, 7, 1)
    return 'XMKECAWLJDB'[sum(int(n) * w for n, w in zip(number, weights)) % 11]
```
Unleashing this function on the data set I found only 11 numbers where the check digit does not match:
```
50856857D
52737212B
52803596X
52804404A
52805118K
52813100D
52853385J
52856860B
52870338A
52882019E
52923950C
```
I have not tried the online validator for these numbers and I haven't looked at the other number types yet but I expect the analysis should be pretty simple to repeat with the approach above (perhaps with some tweaks for the numbers that have letters in them).

**Comment by unho** [comment]
Wow!!!

**Comment by unho** [comment]
@arthurdejong I have checked all those numbers that do not match and they all seem to be either terminated or cancelled in 2017. Maybe we should go with this algorithm?

**Comment by unho** [comment]
Yep, verified with another website and all those are deregistered.

**Comment by arthurdejong** [comment]
I managed to reverse-engineer the local company and other checksums as well (the last one was a much bigger puzzle because of the letters). That only leaves "Foreign Company" numbers (the ones starting with `F000`).

Do you have some examples of valid numbers for these? The one in the tests doesn't pass the [online validator](https://www.iras.gov.sg/irashome/GST/GST-registered-businesses/Other-services/Checking-if-a-Business-is-GST-Registered/ and there do not seem to be many references to this flavour. Also note that the "other" flavour has a code (FC) for foreign companies so perhaps it has been replaced?

Do you have some more background and/or examples of valid "Foreign Company" numbers?

Thanks.

**Comment by unho** [comment]
Sadly I have found no foreign company UEN numbers. If I correctly recall the examples used in testing for foreign companies were made up, while all the examples for the other types of UEN numbers are real examples.

**Comment by arthurdejong** [comment]
Are you OK if I merge it without the foreign company UEN numbers? If it is used and some valid numbers are not validated correctly someone will likely complain while no one will likely complain if an invalid number is considered valid.

**Comment by unho** [comment]
@arthurdejong I am 100% ok with that.

**Pull request closed without merging**
